const std = @import("std");
const interface = @import("interface.zig");

// ═══════════════════════════════════════════════════════════════════════════════
// MANGOHUD TINKER (Phase 3.5 - Hardened, Zig 0.15.x)
// ═══════════════════════════════════════════════════════════════════════════════
//
// No global state! Reads config from ctx.game_config.mangohud
//
// ═══════════════════════════════════════════════════════════════════════════════

fn isEnabled(ctx: *const interface.Context) bool {
    return ctx.game_config.mangohud.enabled;
}

fn modifyEnv(ctx: *const interface.Context, env: *interface.EnvMap) !void {
    const cfg = &ctx.game_config.mangohud;
    
    // Enable MangoHud
    try env.put("MANGOHUD", "1");
    try env.put("MANGOHUD_DLSYM", "1");

    // Build config file content using a fixed buffer
    var config_buf: [4096]u8 = undefined;
    var stream = std.io.fixedBufferStream(&config_buf);
    const writer = stream.writer();

    try writer.writeAll("# MangoHud config generated by STL-Next\n\n");
    try writer.print("position={s}\n", .{cfg.position});

    if (cfg.show_fps) try writer.writeAll("fps\n");
    if (cfg.show_frametime) try writer.writeAll("frametime\nframe_timing\n");
    if (cfg.show_cpu) try writer.writeAll("cpu_stats\ncpu_load_change\n");
    if (cfg.show_gpu) try writer.writeAll("gpu_stats\n");
    if (cfg.show_vram) try writer.writeAll("vram\n");
    if (cfg.show_ram) try writer.writeAll("ram\n");
    if (cfg.show_cpu_temp) try writer.writeAll("cpu_temp\n");
    if (cfg.show_gpu_temp) try writer.writeAll("gpu_temp\n");
    try writer.print("font_size={d}\n", .{cfg.font_size});

    // Write config file
    const config_path = try std.fmt.allocPrint(
        ctx.allocator,
        "{s}/MangoHud",
        .{ctx.config_dir},
    );
    defer ctx.allocator.free(config_path);

    std.fs.makeDirAbsolute(config_path) catch |err| {
        if (err != error.PathAlreadyExists) return err;
    };

    const file_path = try std.fmt.allocPrint(
        ctx.allocator,
        "{s}/wine-{d}.conf",
        .{ config_path, ctx.app_id },
    );
    defer ctx.allocator.free(file_path);

    const file = try std.fs.createFileAbsolute(file_path, .{});
    defer file.close();
    try file.writeAll(stream.getWritten());

    try env.put("MANGOHUD_CONFIG", file_path);

    std.log.info("MangoHud: Enabled (config: {s})", .{file_path});
}

pub const mangohud_tinker = interface.Tinker{
    .id = "mangohud",
    .name = "MangoHud",
    .priority = interface.Priority.OVERLAY,
    .isEnabledFn = isEnabled,
    .preparePrefixFn = null,
    .modifyEnvFn = modifyEnv,
    .modifyArgsFn = null,
    .cleanupFn = null,
};
