const std = @import("std");
const interface = @import("interface.zig");

// ═══════════════════════════════════════════════════════════════════════════════
// MANGOHUD TINKER: Performance Overlay
// ═══════════════════════════════════════════════════════════════════════════════
//
// MangoHud is a Vulkan/OpenGL overlay that displays performance metrics.
// This tinker handles:
// 1. Environment variable injection (MANGOHUD=1, MANGOHUD_CONFIG)
// 2. Per-game config file generation
//
// ═══════════════════════════════════════════════════════════════════════════════

/// MangoHud configuration options
pub const MangoHudConfig = struct {
    enabled: bool = false,
    
    // Display options
    show_fps: bool = true,
    show_frametime: bool = true,
    show_cpu: bool = true,
    show_gpu: bool = true,
    show_vram: bool = false,
    show_ram: bool = false,
    show_cpu_temp: bool = false,
    show_gpu_temp: bool = true,
    
    // Position
    position: Position = .top_left,
    
    // Style
    font_size: u8 = 24,
    background_alpha: f32 = 0.5,
    
    pub const Position = enum {
        top_left,
        top_right,
        bottom_left,
        bottom_right,
        top_center,
        bottom_center,
    };
    
    /// Generate MangoHud config file content
    pub fn toConfigString(self: *const MangoHudConfig, allocator: std.mem.Allocator) ![]const u8 {
        var config = std.ArrayList(u8).init(allocator);
        const writer = config.writer();
        
        try writer.writeAll("# MangoHud config generated by STL-Next\n\n");
        
        // Position
        const pos_str = switch (self.position) {
            .top_left => "top-left",
            .top_right => "top-right",
            .bottom_left => "bottom-left",
            .bottom_right => "bottom-right",
            .top_center => "top-center",
            .bottom_center => "bottom-center",
        };
        try writer.print("position={s}\n", .{pos_str});
        
        // Display toggles
        if (self.show_fps) try writer.writeAll("fps\n");
        if (self.show_frametime) try writer.writeAll("frametime\nframe_timing\n");
        if (self.show_cpu) try writer.writeAll("cpu_stats\ncpu_load_change\n");
        if (self.show_gpu) try writer.writeAll("gpu_stats\n");
        if (self.show_vram) try writer.writeAll("vram\n");
        if (self.show_ram) try writer.writeAll("ram\n");
        if (self.show_cpu_temp) try writer.writeAll("cpu_temp\n");
        if (self.show_gpu_temp) try writer.writeAll("gpu_temp\n");
        
        // Style
        try writer.print("font_size={d}\n", .{self.font_size});
        try writer.print("background_alpha={d:.2}\n", .{self.background_alpha});
        
        return config.toOwnedSlice();
    }
};

// Global config (would be loaded from game config in real impl)
var global_config: MangoHudConfig = .{ .enabled = false };

/// Set the MangoHud config (called from game config loading)
pub fn setConfig(config: MangoHudConfig) void {
    global_config = config;
}

/// Check if MangoHud is enabled
fn isEnabled(ctx: *const interface.Context) bool {
    _ = ctx; // Context not needed for global config check
    return global_config.enabled;
}

/// Modify environment variables for MangoHud
fn modifyEnv(ctx: *const interface.Context, env: *interface.EnvMap) !void {
    // Enable MangoHud
    try env.put("MANGOHUD", "1");
    try env.put("MANGOHUD_DLSYM", "1");
    
    // Generate per-game config
    const config_content = try global_config.toConfigString(ctx.allocator);
    defer ctx.allocator.free(config_content);
    
    // Write config file
    const config_path = try std.fmt.allocPrint(
        ctx.allocator,
        "{s}/MangoHud/wine-{s}.conf",
        .{ ctx.config_dir, ctx.game_name },
    );
    defer ctx.allocator.free(config_path);
    
    // Ensure directory exists
    const dir_path = std.fs.path.dirname(config_path) orelse return error.InvalidPath;
    std.fs.makeDirAbsolute(dir_path) catch |err| {
        if (err != error.PathAlreadyExists) return err;
    };
    
    // Write config
    const file = try std.fs.createFileAbsolute(config_path, .{});
    defer file.close();
    try file.writeAll(config_content);
    
    // Set config path
    try env.put("MANGOHUD_CONFIG", config_path);
    
    std.log.info("MangoHud: Enabled with config at {s}", .{config_path});
}

/// The MangoHud tinker instance
pub const mangohud_tinker = interface.Tinker{
    .id = "mangohud",
    .name = "MangoHud",
    .priority = interface.Priority.OVERLAY,
    .isEnabledFn = isEnabled,
    .preparePrefixFn = null,
    .modifyEnvFn = modifyEnv,
    .modifyArgsFn = null,
    .cleanupFn = null,
};

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

test "mangohud config generation" {
    const config = MangoHudConfig{
        .enabled = true,
        .show_fps = true,
        .show_gpu = true,
        .position = .top_right,
    };
    
    const content = try config.toConfigString(std.testing.allocator);
    defer std.testing.allocator.free(content);
    
    try std.testing.expect(std.mem.indexOf(u8, content, "position=top-right") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "fps") != null);
}
